name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image (build phase)
      run: docker build -t frankszoo:build --target build .
    - name: Test
      run: docker run frankszoo:build flutter test
    - name: Build the Docker image (packaging phase)
      run: docker build -t frankszoo:edge .
    - name: Create local Docker container
      run: docker create --name container frankszoo:build
    - name: Ensure export directory exists
      run: mkdir -p build
    - name: Export build from container
      run: docker cp container:/src/build/web/ build/
    - name: Export to artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: build/

  deploy:
    environment:
      name: prod
      url: https://www.drksn.nl/frankszoo/
    runs-on: ubuntu-latest
    container: rclone/rclone:latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: web-build
      - name: Set rclone config
        run: echo $RCLONE_CONFIG > ~/.config/rclone/rclone.conf
        env:
          RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
      - name: Copy files
        run: rclone sync . s3:/drksn-website/frankszoo/
