name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image (build phase)
      run: docker build -t frankszoo:build --target build .
    - name: Test
      run: docker run frankszoo:build flutter test
    - name: Build the Docker image (packaging phase)
      run: docker build -t frankszoo:edge .
    - name: Create local Docker container
      run: docker create --name container frankszoo:edge
    - name: Ensure export directory exists
      run: mkdir -p build/web
    - name: Export build from container
      run: docker cp container:/usr/share/nginx/html/ src/build/web/
    - name: Export to artifact
      uses: actions/upload-artifact@v4
      with:
        name: web-build
        path: src/build/web/
