name: Status checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image (build phase)
      run: docker build -t frankszoo:build --target build .
    - name: Test
      run: docker run frankszoo:build flutter test
    - name: Build the Docker image (packaging phase)
      run: docker build -t frankszoo:edge .
